name: cajero_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  intl: ^0.19.0

  # Formularios
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2

  # Utilidades
  http: ^1.2.1
  provider: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/lumina.png
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/lumina.png"
  remove_alpha_ios: true


