// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73ffHhuFqr4aFp1qOLpqFlmv7Zz-T1bo',
    appId: '1:371442000945:web:1af29c30876161d2682110',
    messagingSenderId: '371442000945',
    projectId: 'cajeroapp-f5a48',
    authDomain: 'cajeroapp-f5a48.firebaseapp.com',
    storageBucket: 'cajeroapp-f5a48.firebasestorage.app',
    measurementId: 'G-79ZDV6E7L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfJuxOQsY901u16nQhHy6PTTXK_LifUM',
    appId: '1:371442000945:android:5764959e912a0c2c682110',
    messagingSenderId: '371442000945',
    projectId: 'cajeroapp-f5a48',
    storageBucket: 'cajeroapp-f5a48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgsOTERGTKi1xfvg2r9-BHEJG_NgCwRwU',
    appId: '1:371442000945:ios:d92567f2c0ee5671682110',
    messagingSenderId: '371442000945',
    projectId: 'cajeroapp-f5a48',
    storageBucket: 'cajeroapp-f5a48.firebasestorage.app',
    iosBundleId: 'com.example.cajeroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgsOTERGTKi1xfvg2r9-BHEJG_NgCwRwU',
    appId: '1:371442000945:ios:d92567f2c0ee5671682110',
    messagingSenderId: '371442000945',
    projectId: 'cajeroapp-f5a48',
    storageBucket: 'cajeroapp-f5a48.firebasestorage.app',
    iosBundleId: 'com.example.cajeroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA73ffHhuFqr4aFp1qOLpqFlmv7Zz-T1bo',
    appId: '1:371442000945:web:ceeee8202ef9188a682110',
    messagingSenderId: '371442000945',
    projectId: 'cajeroapp-f5a48',
    authDomain: 'cajeroapp-f5a48.firebaseapp.com',
    storageBucket: 'cajeroapp-f5a48.firebasestorage.app',
    measurementId: 'G-4WR41WDXLB',
  );
}
